### ISSUE TITLE
Errors around Switzerland

### ISSUE THREAD

**Issue by Timon-R** [PyPSA/pypsa-eur#1218]
## Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). 

- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). 

## Describe the Bug

I receive a Name error exception, see below by running: snakemake -call all --use-conda

## Error Message

ERROR:root:Uncaught exception
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/.snakemake/conda/2da1d03b1d698aedcf7e1343aeca92b5_/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/scripts/build_industrial_production_per_country.py", line 253, in industry_production_per_country
    demand *= get_energy_ratio(country, eurostat_dir, jrc_dir, year)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/scripts/build_industrial_production_per_country.py", line 196, in get_energy_ratio
    snakemake.input.ch_industrial_production, index_col=0
    ^^^^^^^^^
NameError: name 'snakemake' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/.snakemake/scripts/tmpff62pc90.build_industrial_production_per_country.py", line 347, in <module>
    demand = industry_production(countries, year, eurostat_dir, jrc_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/.snakemake/scripts/tmpff62pc90.build_industrial_production_per_country.py", line 281, in industry_production
    demand_l = list(tqdm(pool.imap(func, countries), **tqdm_kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/.snakemake/conda/2da1d03b1d698aedcf7e1343aeca92b5_/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/Users/timonr/Library/CloudStorage/OneDrive-Chalmers/Documents/pypsa-eur/.snakemake/conda/2da1d03b1d698aedcf7e1343aeca92b5_/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
NameError: name 'snakemake' is not defined

**Comment by Timon-R** [comment]
The Errors I got trying to fix this revolve around the country Switzerland (CH). If removed from the config, the code works. Otherwise, it bugs.

When I changed the build_industrial_demand script so the snakemake object is passed to the function where it is used, I received an Exception in the simplify_network script saying that something around CH would be missing.

**Comment by Timon-R** [comment]
This got resolved with changing the clusters to 38

**Comment by FabianHofmann** [comment]
I am struggling with the same error atm, do you know why it worked with 38 clusters?

**Comment by Timon-R** [comment]
No idea I don't understand the code enough for that - I assume it has to do with added data on the networks; some links or sth. 

Is it working for you when using 38 clusters? Or do you still get the snakemake error?

**Comment by FabianHofmann** [comment]
I am reopening as the issue is not resolved fully I would say

**Comment by fneum** [comment]
With Corsica resolved as its own synchronous zone (#1215), the minimum number of clusters for the default countries is 38. But the error for Switzerland seems unrelated.
